port: 9000
log_level: info

keys:
  APIE489774A8A86034D: e27ffd8d0268aa8c9f9ef04e2c2e3f7e7b9c69a9f78d2fe979370c073a06f6bb

# Redis is required for LiveKit Egress
redis:
  address: redis:6379

rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: true

room:
  auto_create: true
  empty_timeout: 300
  departure_timeout: 20
